apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: appsec
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: manhduynguyen/web-app:latest
        ports:
        - containerPort: 80  # Nginx chạy port 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"

